intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import x_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/freetype/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{freetype}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{freetype}: {h c}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmia obja}{*}: c.poptions += -DFREETYPE_STATIC_BUILD
{hbmis objs}{*}: c.poptions += -DFREETYPE_SHARED_BUILD

# Export options.
#
lib{freetype}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

liba{freetype}: c.export.poptions += -DFREETYPE_STATIC
libs{freetype}: c.export.poptions += -DFREETYPE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{freetype}: bin.lib.version = "-$version.project_id"
else
  lib{freetype}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
